### ISSUE TITLE
Only seems to work while game is paused

### ISSUE THREAD

**Issue by JonnyOThan** [FirstPersonKSP/KerbTrack#1]

**Comment by ghost** [comment]
I also have this problem, and it was also previously mentioned by @DanielKinsman (who added support for OpenTrack): https://github.com/pizzaoverhead/KerbTrack/pull/7.

I have noticed that, on IVA, with FreeIVA installed, you can create a similar issue by getting out of your seat and then getting back in. After you do that, the camera will only move when the game is paused. (I also verified that the issue in flight mode is present regardless of whether or not FreeIVA is installed.)

I did some debugging, and the branch to update the camera in when flight mode (https://github.com/JonnyOThan/KerbTrack/blob/ef7f1a85d73e972b8a87f20ee2976038c96bbe84/KerbTrack/KerbTrack.cs#L423C38-L423C38), is indeed running, and producing reasonable values for pv, yv, and rv, even when the game is un-paused. So, it doesn't appear to be a simple bug affecting control- or data- flow in KerbTrack. I am guessing that something external to KerbTrack might be causing issues.

I will try to figure out what FreeIVA is changing when you get out of your seat and get back in. Maybe that will shed some light on what is happening in flight mode.

**Comment by brianmwaters** [comment]
I got it to work. The code is missing a call to `FlightCamera.fetch.DeactivateUpate()`. Without this, it seems like KSP overrides our head tracking input.

What I have at the moment is not ready for submission (it's putting the camera right in the middle of the vessel), but that is the basic problem.

**Comment by ghost** [comment]
Fixed in https://github.com/JonnyOThan/KerbTrack/pull/9

**Comment by JonnyOThan** [comment]
This is happening because FlightCamera overwrites its transform at the end of its LateUpdate.  Either we need to run code *after* that point to alter the transform, or we could insert a gameobject as a parent of the camera object and update its transform.  Modifying the transform after lateUpdate would likely require harmony.  KerbalVR uses an empty gameobject transform, but the circumstances are a little different - in VR the tracking systems inject their transforms into the gameobjects that contain the camera, so the extra anchor transform is necessary for any game logic that wants to drive the camera around.  Our situation is actually reversed.

I believe this is also the root cause of #10 and #5.

**Comment by ghost** [comment]
All of that makes sense, and I agree it's probably the cause of those other bugs.

I didn't get to do any coding today, but I did upgrade my test setup to support both translation and TrackIR (via Wine)!

In the meantime here is a fun image of Jeb taking his head off when translation is enabled:
![headless-kerbal](https://github.com/JonnyOThan/KerbTrack/assets/12619481/b8ca8a3a-79c9-41d7-bc74-0c1268b254f0)
