### ISSUE TITLE
Remove Windows-specific code in csproj file

### ISSUE THREAD

**Issue by ghost** [FirstPersonKSP/KerbTrack#12]
There's some cmd.exe stuff in there that initially prevented me from building this on Linux/Mono

**Comment by ghost** [comment]
I'm using xbuild, and need to figure out how to install msbuild on Gentoo before I can work on this.

**Comment by JonnyOThan** [comment]
There's no cmd.exe stuff in the csproj file in my fork.  Are you referring to the xcopy postbuild step?

**Comment by JonnyOThan** [comment]
I made the xcopy step conditional on windows, feel free to add whatever is the equivalent, conditional on your OS.

**Comment by ghost** [comment]
That's perfect, thank you.
