### ISSUE TITLE
Mouse offset when plugin enabled in Flight View

### ISSUE THREAD

**Issue by ghost** [FirstPersonKSP/KerbTrack#5]
When in flight view, with the plugin enabled, there is an offset between the cursor's actual position, as animated, and it's _effective position_. See the attached screenshot, which shows a part on the vessel being highlighted, despite the mouse cursor being somewhat to the right of the part itself.

What's more; when using OpenTrack (haven't tried other methods), when you move your head around, it actually changes the offset. So you can hold the mouse cursor in one place, and actually highlight different parts on the vessel by moving your head around.

This only seems to affect highlighting/clicking on vessel parts (to bring up the little orange context menu); it doesn't seem to affect the context menus themselves, or other in-game UI elements. I haven't tested in IVA or map mode.

After having a read through `KerbTrack.cs`, I think the code could use some clean-up, and I am sure that this problem is simply a result of some variable being used inconsistently or something like that.

![offset](https://github.com/JonnyOThan/KerbTrack/assets/12619481/759dd351-97d5-433e-bb17-1e9fe942fb85)

**Comment by ghost** [comment]
Related to https://github.com/JonnyOThan/KerbTrack/issues/1, and fixed in https://github.com/JonnyOThan/KerbTrack/pull/9.

**Comment by JonnyOThan** [comment]
The part selection should be operating off a raycast using the camera transform, maybe KerbTrack is updating the transform too late for this to work properly.

relevant stock code: Mouse.CheckHoveredPart

**Comment by JonnyOThan** [comment]
This is now fixed with https://github.com/JonnyOThan/KerbTrack/commit/cde3c34b8d0db7233bdba695de4c156b72f2509d
